version: '3.8'
services:
  app:
    build: .
    ports:
      - "3007:3007"
    volumes:
      - .:/app
    volumes:
      - .:/app
      - /app/node_modules

    environment:
      NODE_ENV: production